name: 'Coverlet coverage test'
description: 'Run coverlet coverage using a msbuild.rsp generated configuation'
inputs:
  output:  # id of input
    description: 'output filename'
    required: true
    default: './lcov.info'
  outputFormat:
    description: 'output format : lcov, json, opencover, corbertura, temacity (see coverlet documentation)' 
    required: true
    default : 'lcov'
  excludes:
    description: 'assemblies, namespances exclusions (see coverlet documentation)'
    required: false
  testProject:
    description: 'path to unit test project from repository root'    
    required: true
runs:
  using: 'node12'
  #pre: 'setup.js'
  main: 'index.js'
  #post: 'cleanup.js'