name: 'Coverlet coverage test'
description: 'Run coverlet coverage using a msbuild.rsp generated configuration'
inputs:
  output:  # id of input
    description: 'output filename'
    required: true
    default: './lcov.info'
  outputFormat:
    description: 'output format : lcov, json, opencover, cobertura, teamcity (see coverlet documentation)' 
    required: true
    default : 'lcov'
  excludes:
    description: 'assemblies, namespaces, exclusions (see coverlet documentation)'
    required: false
  testProject:
    description: 'path to unit test project file or solution file from repository root'    
    required: true
  threshold:
    description: 'threshold below which tests fail.'
    required: false
  debug:
    description: 'if true, produces extra debugging output. Default is false.'
    required: false
outputs:
  coverageFile:
    description: 'path to the generated coverage file'     
runs:
  using: 'node20'
  #pre: 'setup.js'
  main: 'index.js'
  #post: 'cleanup.js'
branding:
  icon: 'check-circle'  
  color: 'green'
